name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [php8.3, php8.4]

    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-dist --no-cache'

      - name: Run tests
        run: vendor/bin/pest
